[package]
name = "cube-tui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.25.0"
float-ord = "0.3.2"
ordered-float = "3.4.0"
rand = "0.8.5"
rand_derive = "0.5.0"
tui = "0.19.0"
